git:
  depth: 1
jobs:
  include:
    - language: python
      python: '3.6'
      cache: pip
      install:
        - pip install -r requirements.txt
        - pip install codecov
      script:
        - python manage.py makemigrations
        - python manage.py test
        - coverage run --source=. manage.py test #push my coverage score on a coverage tracker service
      after_success:
        - codecov #push my coverage score on a coverage tracker service

    - stage: before_deploy
      # this is to avoid any commits on branche different than the master to push new images on dockerHub
      if: repo = WilliamsRizzi/how_to_CI_CD AND branch = master AND type = push
      language: minimal
      name: Build Docker image and push to Docker Hub registry
      services: docker
      # push the new build on dockerHub both as 'latest version and as git tag
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t willo05/how_to_ci_cd:$TRAVIS_COMMIT .
        - docker build -t willo05/how_to_ci_cd .
        - docker push willo05/how_to_ci_cd:$TRAVIS_COMMIT
        - docker push willo05/how_to_ci_cd

#    - stage: deploy
#      if: repo = WilliamsRizzi/how_to_CI_CD AND branch = master AND type = push
#      dist: xenial
#      name: Server deployment
#      language: minimal
#      deploy:
#        provider: script
#        skip_cleanup: true
#        script: bash deploy.sh
