git:
  depth: 1
jobs:
  include:
    - language: python
      python: '3.6'
      cache: pip
      install:
        - pip install -r requirements.txt
        - pip install codecov
      script:
        - python manage.py makemigrations
        - python manage.py test
        - coverage run --source=. manage.py test
      after_success:
        - codecov

    - stage: before_deploy
      if: repo = WilliamsRizzi/how_to_ci_cd AND branch = master AND type = push
      language: minimal
      name: Build Docker image and push to Docker Hub registry
      services: docker
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t willo05/how_to_ci_cd:$TRAVIS_COMMIT .
        - docker build -t willo05/how_to_ci_cd .
        - docker push willo05/how_to_ci_cd:$TRAVIS_COMMIT
        - docker push willo05/how_to_ci_cd

    - stage: deploy
      if: repo = WilliamsRizzi/how_to_ci_cd AND branch = master AND type = push
      dist: xenial
      name: Server deployment
      language: minimal
      deploy:
        provider: script
        skip_cleanup: true
        script: bash deploy.sh
