version: "3.4"
services:

  server:
    image: willo05/how_to_ci_cd
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    ports:
      - 80:8000
